seed = 0
parent_dir = "exp/bodmas/many-exps/48"
real_data_path = "data/bodmas/"
model_type = "mlp"
num_numerical_features = 2381
device = "cuda:0"

[model_params]
num_classes = 10
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    1024,
    128,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 20000
lr = 0.0005850263178419634
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 1532
batch_size = 1000
seed = 4

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"
